apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

images:
- name: demo-client
  newName: localhost:5001/demo-client
- name: demo-server
  newName: localhost:5001/demo-server

commonLabels:
  demo: "true"

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: demo-client-headless
    path: rename.yaml
