apiVersion: apps/v1
kind: Deployment
metadata:
  labels: { app: demo-server }
  name: demo-server
spec:
  replicas: 1
  selector:
    matchLabels: { app: demo-server }
  template:
    metadata:
      labels: { app: demo-server }
    spec:
      containers:
      - image: demo-server
        name: demo-server
        envFrom: [configMapRef: { name: jaeger }]
---
apiVersion: v1
kind: Service
metadata:
  labels: { app: demo-server }
  name: demo-server
spec:
  clusterIP: None
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector: { app: demo-server }