apiVersion: v1
kind: Service
metadata:
  name: demo-server-clusterip
spec:
  type: ClusterIP
  selector: { app: demo-server }
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: demo-server-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector: { app: demo-server }
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
